import {
  Dumbbell,
  Brain,
  BookOpen,
  Moon,
  Droplet,
  Heart,
  Apple,
  Coffee,
  Footprints,
  Music,
  Palette,
  Code,
  Briefcase,
  Users,
  Phone,
  Camera,
  Smile,
  Target,
  Zap,
  CheckCircle,
} from 'lucide-react';

export const HABIT_ICONS = {
  'dumbbell': Dumbbell,
  'exercise': Dumbbell,
  'brain': Brain,
  'meditation': Brain,
  'book': BookOpen,
  'reading': BookOpen,
  'moon': Moon,
  'sleep': Moon,
  'droplet': Droplet,
  'hydration': Droplet,
  'water': Droplet,
  'heart': Heart,
  'apple': Apple,
  'nutrition': Apple,
  'coffee': Coffee,
  'footprints': Footprints,
  'walking': Footprints,
  'music': Music,
  'palette': Palette,
  'art': Palette,
  'code': Code,
  'briefcase': Briefcase,
  'work': Briefcase,
  'users': Users,
  'social': Users,
  'phone': Phone,
  'camera': Camera,
  'smile': Smile,
  'target': Target,
  'zap': Zap,
  'check-circle': CheckCircle,
};

export const HABIT_ICON_OPTIONS = [
  { value: 'exercise', label: 'Exercise', color: '#EF4444' },
  { value: 'meditation', label: 'Meditation', color: '#8B5CF6' },
  { value: 'reading', label: 'Reading', color: '#3B82F6' },
  { value: 'sleep', label: 'Sleep', color: '#6366F1' },
  { value: 'hydration', label: 'Hydration', color: '#06B6D4' },
  { value: 'nutrition', label: 'Nutrition', color: '#10B981' },
  { value: 'walking', label: 'Walking', color: '#F59E0B' },
  { value: 'music', label: 'Music', color: '#EC4899' },
  { value: 'art', label: 'Art', color: '#F97316' },
  { value: 'code', label: 'Coding', color: '#14B8A6' },
  { value: 'work', label: 'Work', color: '#6B7280' },
  { value: 'social', label: 'Social', color: '#84CC16' },
];
